/* include sqlReturnInfo */
SELECT 
	ACCOUNT_FROM AS {:ACCOUNT_FROM:string:20}, 
	ACCOUNT_TO AS {:ACCOUNT_TO:string:20}, 
	CLIENT_FIO_FROM AS {:CLIENT_FIO_FROM:string:50}, 
	CLIENT_FIO_TO AS {:CLIENT_FIO_TO:string:50}, 
	CURRENCY AS {:CURRENCY:string:3}, 
	PAYMENT_RUB AS {:PAYMENT_RUB:decimal},  
	TRANSACTION_DTTM AS {:TRANSACTION_DTTM:datetime}, 
	EMP_NUM AS {:EMP_NUM:string:10}
FROM "transactions"
WHERE ACCOUNT_FROM IN ({?:ACCOUNT_FIRST:string:20}, {?:ACCOUNT_SECOND:string:20}) 
AND ACCOUNT_TO IN ({?:ACCOUNT_FIRST:string:20}, {?:ACCOUNT_SECOND:string:20})